- src: geerlingguy.apache
  version: 3.2.0
- src: geerlingguy.php
  version: 3.0.0
- src: geerlingguy.mysql
  version: 2.9.0
- src: geerlingguy.composer
  version: 2.0.0
- src: geerlingguy.nodejs
  version: 2.0.0
- src: oracle.oci
  version: 1.0.0