APP_ENV=prod
APP_DEBUG=0
DATABASE_URL=mysql://dbuser:secret@127.0.0.1:13306/eccube
DATABASE_SERVER_VERSION=8.0.42
DATABASE_CHARSET=utf8mb4
MAILER_DSN=smtp://localhost:25
ECCUBE_LOCALE=ja
ECCUBE_TIMEZONE=Asia/Tokyo
ECCUBE_CURRENCY=JPY
ECCUBE_ADMIN_ROUTE=admin
ECCUBE_USER_DATA_ROUTE=user_data
ECCUBE_ADMIN_ALLOW_HOSTS=[]
ECCUBE_ADMIN_DENY_HOSTS=[]
ECCUBE_FORCE_SSL=false
ECCUBE_PHPINFO_ENABLED=false
ECCUBE_TEMPLATE_CODE=default
ECCUBE_AUTH_MAGIC=<change.me>
ECCUBE_COOKIE_NAME=eccube
ECCUBE_COOKIE_PATH=/
ECCUBE_COOKIE_LIFETIME=0
ECCUBE_GC_MAXLIFETIME=1440
ECCUBE_ADMIN_USER=admin
ECCUBE_ADMIN_PASS=password
ECCUBE_2FA_ENABLED=true
ECCUBE_2FA_COOKIE_NAME=eccube_2fa
ECCUBE_2FA_EXPIRE=14
ECCUBE_RESTRICT_FILE_UPLOAD=0
TRUSTED_HOSTS=^127\.0\.0\.1$,^192\.168\.0\.61$