---
- name: Detect OS family
  set_fact:
    is_ubuntu: "{{ ansible_os_family == 'Debian' }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: '0755'

- name: Install Composer globally
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Set Composer permissions
  file:
    path: /usr/local/bin/composer
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Composer config directory
  file:
    path: "{{ ansible_user_dir }}/.composer"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Configure Composer
  composer:
    command: config
    arguments: --global process-timeout 2000
    global_command: true
  become: yes
  environment:
    COMPOSER_HOME: "{{ ansible_user_dir }}/.composer"
    COMPOSER_ALLOW_SUPERUSER: "1"